// Seed data for /admin moderation queue.
// Mix of Open/Hidden/Resolved across all content types, citizen+rep reporters.

window.AD_REPORTS = [
  {
    id: 14207,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88341',
    targetHost: 'Byron Donalds · post #2210',
    preview: "This is just more partisan garbage from a career politician who clearly doesn't care about anyone in FL-19. He should be ashamed.",
    author: 'Maria H. (citizen)',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Personal attack on a public official, repeat behavior on this account.',
    reporter: 'Office of B. Donalds',
    reporterKind: 'rep',
    autoFlag: false,
    when: '12m ago',
    whenAbs: 'Today 10:14 AM',
    status: 'open',
  },
  {
    id: 14206,
    type: 'post',
    typeLabel: 'Rep post',
    targetId: 'post#2208',
    targetHost: 'Rep · J. Rivera-Cantú',
    preview: 'Just confirmed — every dollar of the new infrastructure bill is going directly into private contractor pockets. Sources next week.',
    author: 'Rep · J. Rivera-Cantú',
    authorRole: 'rep',
    reason: 'Misinformation',
    reasonKey: 'misinfo',
    reasonDetail: 'Claim is unverifiable; no source attached. Three other citizens reported.',
    reporter: 'David Okafor',
    reporterKind: 'citizen',
    autoFlag: true,
    when: '47m ago',
    whenAbs: 'Today 9:39 AM',
    status: 'open',
  },
  {
    id: 14205,
    type: 'pollcomment',
    typeLabel: 'Comment on poll',
    targetId: 'pollcomment#3104',
    targetHost: 'Poll · "Support SB-440?"',
    preview: 'Anyone voting yes on this is genuinely brain-damaged. Look around at what these people have done to our state.',
    author: 'Travis K. (citizen)',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Insulting other voters; second report this week.',
    reporter: 'Rep · M. Alvarez',
    reporterKind: 'rep',
    autoFlag: false,
    when: '1h ago',
    whenAbs: 'Today 9:08 AM',
    status: 'hidden',
  },
  {
    id: 14204,
    type: 'poll',
    typeLabel: 'Citizen poll',
    targetId: 'poll#4471',
    targetHost: 'Citizen poll · "Should the mayor resign?"',
    preview: 'Should the mayor resign? Click to claim your free $500 gift card while you decide — limited time link in bio →',
    author: 'free_offer_bot',
    authorRole: 'citizen',
    reason: 'Spam',
    reasonKey: 'spam',
    reasonDetail: 'Affiliate link, account created 2h ago, no other activity.',
    reporter: 'Auto-detect',
    reporterKind: 'system',
    autoFlag: true,
    when: '2h ago',
    whenAbs: 'Today 8:11 AM',
    status: 'open',
  },
  {
    id: 14203,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88298',
    targetHost: 'Byron Donalds · post #2204',
    preview: 'You all sound exactly like the people you claim to hate. Maybe touch grass.',
    author: 'pinetree_42 (citizen)',
    authorRole: 'citizen',
    reason: 'Off-topic',
    reasonKey: 'offtopic',
    reasonDetail: '',
    reporter: 'Linda S.',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '3h ago',
    whenAbs: 'Today 7:02 AM',
    status: 'open',
  },
  {
    id: 14201,
    type: 'post',
    typeLabel: 'Rep post',
    targetId: 'post#2199',
    targetHost: 'Rep · K. Whitfield',
    preview: 'The water rates in Lee County are illegal. I have proof and will be filing suit Monday. Names attached.',
    author: 'Rep · K. Whitfield',
    authorRole: 'rep',
    reason: 'Misinformation',
    reasonKey: 'misinfo',
    reasonDetail: 'Names of private individuals attached without consent; cease-and-desist on file from county counsel.',
    reporter: 'Lee County Counsel',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '6h ago',
    whenAbs: 'Today 4:23 AM',
    status: 'hidden',
  },
  {
    id: 14199,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88012',
    targetHost: 'Rep · A. Patel · post #2188',
    preview: 'great post, totally agree we need to do something about this',
    author: 'thomasf',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Reporter retracted: "Sorry — misclick."',
    reporter: 'martin_p',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '1d ago',
    whenAbs: 'Yesterday',
    status: 'resolved',
    resolution: 'Dismissed',
  },
  {
    id: 14196,
    type: 'pollcomment',
    typeLabel: 'Comment on poll',
    targetId: 'pollcomment#3088',
    targetHost: 'Poll · "Beach restoration funds"',
    preview: 'Buy followers cheap! Real US accounts → linkinbio.example',
    author: 'engage_pro_99',
    authorRole: 'citizen',
    reason: 'Spam',
    reasonKey: 'spam',
    reasonDetail: '',
    reporter: 'Auto-detect',
    reporterKind: 'system',
    autoFlag: true,
    when: '2d ago',
    whenAbs: 'Mon, May 13',
    status: 'resolved',
    resolution: 'Author suspended',
  },
];

window.AD_KPIS = {
  open: 5,
  hidden: 12,
  resolvedWeek: 47,
};
