/* CivicView /polls — seed data for the prototype.

   Three data sets:
     POLLS_SEED     — poll cards (rep / citizen / standalone / candidate)
     POSTS_SEED     — post cards (rep / candidate only)
     COMMENTS_SEED  — keyed by card id; lazy-loaded into the inline thread

   Cross-feed linking:
     A post with attached poll appears in BOTH feeds. The post card has
     `attachedPollId`; the poll card has `fromPostId`. Both link to the
     parent rep page.

   `branch` values: 'states' | 'congress' | 'executive' | 'judicial' | 'standalone'
   (was 'bill' / 'committee' — renamed per Reqs.) */

window.POLLS_SEED = [
  {
    id: 'p1',
    kind: 'rep',
    branch: 'states',
    state: 'FL',
    source: { code: 'BD · FL-19', label: 'Byron Donalds — FL-19' },
    author: { name: 'Byron Donalds', initials: 'BD', role: 'U.S. Representative · FL-19', avatarTone: 'rep', verified: true },
    time: '14m ago',
    question: 'Should Congress extend the 2025 SALT cap relief through 2030?',
    options: [
      { id: 'a', label: 'Yes — keep relief in place',  votes: 8420, pct: 64, mine: true,  leading: true },
      { id: 'b', label: 'Phase it out gradually',      votes: 3680, pct: 28 },
      { id: 'c', label: 'Let it expire on schedule',   votes: 1050, pct:  8 },
    ],
    totalVotes: 13150,
    likes: 412, dislikes: 38, comments: 612,
    closesIn: '2d 4h',
    aiTags: ['informative', 'supportive'],
    fromPostId: 'post-bd-1',  // cross-feed: this poll is attached to post-bd-1
  },
  {
    id: 'p2',
    kind: 'rep',
    branch: 'executive',
    state: 'DC',
    source: { code: 'EXEC', label: 'Executive Branch' },
    author: { name: 'Donald J. Trump', initials: 'DJT', role: 'President of the United States', avatarTone: 'rep', verified: true },
    time: '1h ago',
    question: 'Which infrastructure priority should the administration push first in Q3?',
    options: [
      { id: 'a', label: 'Power grid modernization',     votes: 6720, pct: 42, leading: true },
      { id: 'b', label: 'Port + rail freight upgrades', votes: 4400, pct: 28 },
      { id: 'c', label: 'Interstate bridge backlog',    votes: 3120, pct: 19 },
      { id: 'd', label: 'Rural broadband buildout',     votes: 1750, pct: 11 },
    ],
    totalVotes: 15990,
    likes: 1840, dislikes: 612, comments: 1840,
    closesIn: '6h',
    aiTags: ['critical', 'informative'],
  },
  {
    id: 'p3',
    kind: 'rep',
    branch: 'judicial',
    state: 'DC',
    source: { code: 'SCOTUS', label: 'Supreme Court of the United States' },
    author: { name: 'Office of the Court', initials: 'SC', role: 'Public engagement poll · non-binding', avatarTone: 'rep', verified: true },
    time: '3h ago',
    question: 'Should oral-argument audio be released same-day instead of week-of?',
    options: [
      { id: 'a', label: 'Yes — same-day release',     votes: 9410, pct: 71, leading: true },
      { id: 'b', label: 'Keep the current schedule',  votes: 2880, pct: 22 },
      { id: 'c', label: 'Decide case-by-case',        votes:  920, pct:  7 },
    ],
    totalVotes: 13210,
    likes: 287, dislikes: 14, comments: 487,
    closesIn: '1d 12h',
    aiTags: ['supportive'],
  },
  {
    id: 'p4',
    kind: 'rep',
    branch: 'congress',
    state: 'CA',
    source: { code: 'CA-12', label: 'Nancy Pelosi — CA-12' },
    author: { name: 'Nancy Pelosi', initials: 'NP', role: 'U.S. Representative · CA-12', avatarTone: 'rep', verified: true },
    time: '5h ago',
    question: 'Where should the next federal climate-resilience grant pilot land?',
    options: [
      { id: 'a', label: 'Coastal flood-zone retrofits', votes: 4220, pct: 38 },
      { id: 'b', label: 'Wildfire defensible-space',   votes: 3680, pct: 33, leading: true, mine: true },
      { id: 'c', label: 'Urban heat-island mitigation', votes: 2110, pct: 19 },
      { id: 'd', label: 'Inland drought watersheds',   votes: 1110, pct: 10 },
    ],
    totalVotes: 11120,
    likes: 142, dislikes: 22, comments: 298,
    closesIn: '4d',
    aiTags: ['informative', 'positive'],
  },
  {
    id: 'p5',
    kind: 'citizen',
    branch: 'executive',
    state: 'FL',
    source: { code: 'BD · FL-19', label: 'Posted on Byron Donalds\u2019s page' },
    author: { name: 'Marisol Vega', initials: 'MV', role: 'Constituent · FL-19', avatarTone: 'citizen', verified: false },
    time: '22m ago',
    question: 'Has the SW-Florida hurricane-relief portal worked for you this season?',
    options: [
      { id: 'a', label: 'Yes — got a response in under a week', votes:  920, pct: 14 },
      { id: 'b', label: 'Eventually, but it took weeks',        votes: 2410, pct: 38, leading: true },
      { id: 'c', label: 'Submitted and never heard back',       votes: 2180, pct: 34 },
      { id: 'd', label: 'Haven\u2019t needed it',               votes:  870, pct: 14 },
    ],
    totalVotes: 6380,
    likes: 92, dislikes: 14, comments: 412,
    closesIn: '3d',
    aiTags: ['critical', 'skeptical'],
  },
  {
    id: 'p6',
    kind: 'citizen',
    branch: 'congress',
    state: 'TX',
    source: { code: 'TX-23 (unclaimed)', label: 'Citizen poll on an unclaimed page' },
    author: { name: 'Daniel R. Chen', initials: 'DC', role: 'Constituent · TX-23', avatarTone: 'citizen', verified: false },
    time: '2h ago',
    question: 'Which one issue do you most want the next TX-23 rep to lead on in their first session?',
    options: [
      { id: 'a', label: 'Border-county infrastructure', votes: 1820, pct: 42, leading: true },
      { id: 'b', label: 'Water-rights modernization',  votes: 1130, pct: 26 },
      { id: 'c', label: 'Rural healthcare access',     votes:  900, pct: 21 },
      { id: 'd', label: 'Small-business permits',      votes:  470, pct: 11 },
    ],
    totalVotes: 4320,
    likes: 64, dislikes: 8, comments: 198,
    closesIn: '12h',
    aiTags: ['informative', 'critical'],
  },
  {
    id: 'p7',
    kind: 'citizen',
    branch: 'congress',
    state: 'NY',
    source: { code: 'NY-14', label: 'Posted on A. Ocasio-Cortez\u2019s page' },
    author: { name: 'Priya Subramaniam', initials: 'PS', role: 'Constituent · NY-14', avatarTone: 'citizen', verified: false },
    time: '6h ago',
    question: 'Town-hall format you\u2019d actually show up to?',
    options: [
      { id: 'a', label: 'In-person, evening, neighborhood-local', votes: 3210, pct: 51, mine: true, leading: true },
      { id: 'b', label: 'Live-streamed with text Q&A',           votes: 1880, pct: 30 },
      { id: 'c', label: 'Saturday morning, central venue',       votes:  720, pct: 12 },
      { id: 'd', label: 'Telephone town hall',                    votes:  430, pct:  7 },
    ],
    totalVotes: 6240,
    likes: 84, dislikes: 6, comments: 287,
    closesIn: '5d',
    aiTags: ['supportive', 'positive'],
  },
  {
    id: 'p8',
    kind: 'standalone',
    branch: 'standalone',
    state: 'IL',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'Andre Boyle', initials: 'AB', role: 'Standalone civic poll · IL-13', avatarTone: 'standalone', verified: false, isMe: true },
    time: '45m ago',
    question: 'Ranked-choice voting in federal primaries — where do you land?',
    options: [
      { id: 'a', label: 'Adopt nationally',           votes: 9820, pct: 47, leading: true },
      { id: 'b', label: 'Let states decide',          votes: 6720, pct: 32 },
      { id: 'c', label: 'Keep first-past-the-post',   votes: 3680, pct: 18 },
      { id: 'd', label: 'Not sure yet',               votes:  720, pct:  3 },
    ],
    totalVotes: 20940,
    likes: 412, dislikes: 92, comments: 2104,
    closesIn: '6d',
    aiTags: ['informative', 'critical'],
  },
  {
    id: 'p9',
    kind: 'standalone',
    branch: 'standalone',
    state: 'WA',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'Olivia Mendez', initials: 'OM', role: 'Standalone civic poll · WA-09', avatarTone: 'standalone', verified: false },
    time: '3h ago',
    question: 'How much do you trust the federal budget process to deliver this year?',
    options: [
      { id: 'a', label: 'A lot',          votes:  410, pct:  4 },
      { id: 'b', label: 'Some',           votes: 1820, pct: 17 },
      { id: 'c', label: 'Not much',       votes: 4180, pct: 39, leading: true, mine: true },
      { id: 'd', label: 'None at all',    votes: 4280, pct: 40 },
    ],
    totalVotes: 10690,
    likes: 248, dislikes: 64, comments: 1340,
    closesIn: '1d 6h',
    aiTags: ['skeptical', 'critical'],
  },
  {
    id: 'p10',
    kind: 'standalone',
    branch: 'standalone',
    state: 'CO',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'Jamal Rivers', initials: 'JR', role: 'Standalone civic poll · CO-02', avatarTone: 'standalone', verified: false },
    time: '8h ago',
    question: 'Is "civic education in K-12" something Congress should fund directly?',
    options: [
      { id: 'a', label: 'Yes — direct line item',     votes: 5210, pct: 52, leading: true },
      { id: 'b', label: 'State-level block grants',   votes: 2920, pct: 29 },
      { id: 'c', label: 'Private + nonprofit driven', votes: 1410, pct: 14 },
      { id: 'd', label: 'No federal role',            votes:  510, pct:  5 },
    ],
    totalVotes: 10050,
    likes: 184, dislikes: 22, comments: 762,
    closesIn: '4d',
    aiTags: ['supportive', 'informative'],
  },
  {
    id: 'p11',
    kind: 'candidate',
    branch: 'congress',
    state: 'WA',
    source: { code: 'WA-07 candidate', label: 'Sarah-Jane Liu — running for WA-07' },
    author: { name: 'Sarah-Jane Liu', initials: 'SL', role: 'Candidate · WA-07', avatarTone: 'candidate', verified: true },
    time: '11h ago',
    question: 'Should the FAA require domestic carriers to publish on-time stats per route, not just per airline?',
    options: [
      { id: 'a', label: 'Yes — per-route disclosure', votes: 7120, pct: 78, leading: true },
      { id: 'b', label: 'Per-airline is enough',      votes: 1480, pct: 16 },
      { id: 'c', label: 'Other / no opinion',         votes:  540, pct:  6 },
    ],
    totalVotes: 9140,
    likes: 142, dislikes: 18, comments: 318,
    closesIn: '2d',
    aiTags: ['supportive', 'informative'],
  },
  {
    id: 'p12',
    kind: 'citizen',
    branch: 'states',
    state: 'FL',
    source: { code: 'FL-15', label: 'Posted on L. Lee\u2019s page' },
    author: { name: 'Jasmine O\u2019Connor', initials: 'JO', role: 'Constituent · FL-15', avatarTone: 'citizen', verified: false },
    time: '1d ago',
    question: 'Pick the property-tax reform you\u2019d back if it hit the ballot tomorrow:',
    options: [
      { id: 'a', label: 'Homestead-only deeper cap',         votes:  920, pct: 24 },
      { id: 'b', label: 'Senior + disabled veteran freeze',  votes: 1450, pct: 38, leading: true },
      { id: 'c', label: 'Tier reform for second homes',      votes:  850, pct: 22 },
      { id: 'd', label: 'Hold the line; reform later',       votes:  610, pct: 16 },
    ],
    totalVotes: 3830,
    likes: 38, dislikes: 4, comments: 142,
    closesIn: '8h',
    aiTags: ['critical', 'informative'],
  },
];

/* POSTS_SEED — verified reps + candidates only. Sort: engagement-score
   (likes + dislikes + comments + votes), desc. Tiebreaker = recency. */
window.POSTS_SEED = [
  {
    id: 'post-bd-1',
    kind: 'rep',
    branch: 'states',
    state: 'FL',
    source: { code: 'BD · FL-19', label: 'Byron Donalds — FL-19' },
    author: { name: 'Byron Donalds', initials: 'BD', role: 'U.S. Representative · FL-19', avatarTone: 'rep', verified: true },
    time: '14m ago',
    body: 'Update from D.C. — and a real one this time, not press-release boilerplate.\n\nAfter 14 months of negotiation, a midnight markup that ran past 2 a.m. last Tuesday, and three amendments I personally rewrote on a napkin in the cloakroom, H.R. 4421 — the Rural Connectivity and Digital Equity Act — passed the floor 218 to 207. It now heads to the Senate, where the path is steeper, but for the first time this Congress we have a bipartisan vehicle moving. I want to be specific about what got watered down and what survived…',
    summarized: true,
    attachedPollId: 'p1',
    likes: 412, dislikes: 38, comments: 612,
    aiTags: ['informative', 'supportive'],
  },
  {
    id: 'post-djt-1',
    kind: 'rep',
    branch: 'executive',
    state: 'DC',
    source: { code: 'EXEC', label: 'Executive Branch' },
    author: { name: 'Donald J. Trump', initials: 'DJT', role: 'President of the United States', avatarTone: 'rep', verified: true },
    time: '1h ago',
    body: 'Just back from the infrastructure summit in Pittsburgh. Three takeaways from the governors in the room — and these will shape our Q3 priorities. Power grid first; everything else hinges on it. Ports + rail freight second. Bridges third, with a 90-day backlog review starting next week. Rural broadband stays in the package but tracks on a different timeline. Full readout coming Friday.',
    likes: 1840, dislikes: 612, comments: 1840,
    aiTags: ['critical', 'informative'],
  },
  {
    id: 'post-np-1',
    kind: 'rep',
    branch: 'congress',
    state: 'CA',
    source: { code: 'CA-12', label: 'Nancy Pelosi — CA-12' },
    author: { name: 'Nancy Pelosi', initials: 'NP', role: 'U.S. Representative · CA-12', avatarTone: 'rep', verified: true },
    time: '4h ago',
    body: 'Climate-resilience grant pilot moves to floor markup next week. Of the four candidate locations our committee shortlisted, the inland-drought watershed pilot landed lowest on the constituent-engagement poll we ran — but it scored highest on technical readiness. So we\u2019re proposing a hybrid: coastal-flood retrofits as the headline pilot, with an inland-drought companion that runs in parallel at a quarter of the budget.',
    likes: 142, dislikes: 22, comments: 298,
    attachedPollId: 'p4',
    aiTags: ['informative', 'positive'],
  },
  {
    id: 'post-pj-1',
    kind: 'rep',
    branch: 'congress',
    state: 'WA',
    source: { code: 'WA-07', label: 'Pramila Jayapal — WA-07' },
    author: { name: 'Pramila Jayapal', initials: 'PJ', role: 'U.S. Representative · WA-07', avatarTone: 'rep', verified: true },
    time: '11h ago',
    body: 'Per-route on-time disclosure passed out of committee 11–8. This is a small win that adds up — passengers in Sea-Tac will be able to see exactly which routes are running late, not just which airlines, before they book. Headed to the full T&I committee next month.',
    likes: 142, dislikes: 18, comments: 318,
    aiTags: ['supportive', 'informative'],
  },
  {
    id: 'post-sl-1',
    kind: 'candidate',
    branch: 'congress',
    state: 'WA',
    source: { code: 'WA-07 candidate', label: 'Sarah-Jane Liu — running for WA-07' },
    author: { name: 'Sarah-Jane Liu', initials: 'SL', role: 'Candidate · WA-07', avatarTone: 'candidate', verified: true },
    time: '1d ago',
    body: 'Three weeks into the campaign and the question I keep getting at door-knocks: "Will you actually show up?" — meaning, will I hold open office hours, will I sit at someone\u2019s kitchen table, will I respond to email. The answer is yes, and we\u2019re publishing the constituent-services workflow as part of our day-one transition plan. Public draft going up next Monday.',
    likes: 92, dislikes: 14, comments: 142,
    aiTags: ['supportive', 'positive'],
  },
  {
    id: 'post-sc-1',
    kind: 'rep',
    branch: 'judicial',
    state: 'DC',
    source: { code: 'SCOTUS', label: 'Supreme Court of the United States' },
    author: { name: 'Office of the Court', initials: 'SC', role: 'Public engagement · non-binding', avatarTone: 'rep', verified: true },
    time: '3h ago',
    body: 'Same-day oral-argument audio publication is under review by the Court\u2019s public-information office. We are taking public input on whether to move from week-of release to same-day. Comments below; aggregate data will be reviewed by the Public Information Officer at the close of the public-comment window.',
    likes: 287, dislikes: 14, comments: 487,
    attachedPollId: 'p3',
    aiTags: ['supportive'],
  },
];

/* COMMENTS_SEED — keyed by card id. Lazy-loaded on thread expansion. */
window.COMMENTS_SEED = {
  'p1': [
    { id: 'c1', author: 'Pat Back', initials: 'PB', location: 'LA-4 · Demo City', verified: false, time: '5/14/2026', body: 'Bro wrote amendments on a napkin in the cloakroom and saved rural internet. Absolute legend behavior.', likes: 1, dislikes: 0, isMe: true },
    { id: 'c2', author: 'Reshanda Bonquiqui', initials: 'RB', location: 'IL-13 · Demo City', verified: false, time: '5/14/2026', body: '$42 per household is not \u2018small.\u2019 That\u2019s $42 per year per family, every year, with no guarantee the audits hold. Why no sunset clause?', likes: 1, dislikes: 0 },
    { id: 'c3', author: 'Tyron Bigums', initials: 'TB', location: 'FL-12 · Melbourne', verified: false, time: '5/14/2026', body: 'Finally — my parents have been on DSL for a decade. Thank you for the milestone-reporting amendment, that\u2019s the part that matters.', likes: 1, dislikes: 0 },
    { id: 'c4', author: 'Holly Tanner', initials: 'HT', location: 'FL-19 · Naples', verified: true, time: '5/14/2026', body: 'Genuine question: when does the Senate version markup begin?', likes: 0, dislikes: 0 },
    { id: 'c5', author: 'Mark Reston', initials: 'MR', location: 'TX-7 · Houston', verified: false, time: '5/13/2026', body: 'Took 14 months. Should\u2019ve taken 4. The horse-trading on the rural-set-aside is what cost us a full session.', likes: 2, dislikes: 1 },
  ],
  'post-bd-1': [
    { id: 'c1', author: 'Pat Back', initials: 'PB', location: 'LA-4 · Demo City', verified: false, time: '5/14/2026', body: 'Bro wrote amendments on a napkin in the cloakroom and saved rural internet. Absolute legend behavior.', likes: 1, dislikes: 0, isMe: true },
    { id: 'c2', author: 'Reshanda Bonquiqui', initials: 'RB', location: 'IL-13 · Demo City', verified: false, time: '5/14/2026', body: '$42 per household is not \u2018small.\u2019 That\u2019s $42 per year per family, every year, with no guarantee the audits hold. Why no sunset clause?', likes: 1, dislikes: 0 },
    { id: 'c3', author: 'Tyron Bigums', initials: 'TB', location: 'FL-12 · Melbourne', verified: false, time: '5/14/2026', body: 'Finally — my parents have been on DSL for a decade. Thank you for the milestone-reporting amendment, that\u2019s the part that matters.', likes: 1, dislikes: 0 },
  ],
  'p8': [
    { id: 'c1', author: 'Lana Forshaw', initials: 'LF', location: 'IL-13 · Demo City', verified: false, time: '5/22/2026', body: 'Adopt nationally only if there\u2019s a clean ballot-design standard with it. Otherwise we just trade one set of confused voters for another.', likes: 4, dislikes: 0 },
    { id: 'c2', author: 'Donovan Reece', initials: 'DR', location: 'WA-03 · Vancouver', verified: false, time: '5/22/2026', body: 'States-decide is the only constitutional answer. Federalism exists for a reason.', likes: 2, dislikes: 5 },
  ],
};

window.AI_FILTER_TAGS = [
  { id: 'positive',    label: 'Positive' },
  { id: 'critical',    label: 'Critical' },
  { id: 'funny',       label: 'Funny' },
  { id: 'supportive',  label: 'Supportive' },
  { id: 'skeptical',   label: 'Skeptical' },
];

window.US_STATES = [
  ['AL','Alabama'],['AK','Alaska'],['AZ','Arizona'],['AR','Arkansas'],
  ['CA','California'],['CO','Colorado'],['CT','Connecticut'],['DE','Delaware'],
  ['DC','District of Columbia'],['FL','Florida'],['GA','Georgia'],['HI','Hawaii'],
  ['ID','Idaho'],['IL','Illinois'],['IN','Indiana'],['IA','Iowa'],
  ['KS','Kansas'],['KY','Kentucky'],['LA','Louisiana'],['ME','Maine'],
  ['MD','Maryland'],['MA','Massachusetts'],['MI','Michigan'],['MN','Minnesota'],
  ['MS','Mississippi'],['MO','Missouri'],['MT','Montana'],['NE','Nebraska'],
  ['NV','Nevada'],['NH','New Hampshire'],['NJ','New Jersey'],['NM','New Mexico'],
  ['NY','New York'],['NC','North Carolina'],['ND','North Dakota'],['OH','Ohio'],
  ['OK','Oklahoma'],['OR','Oregon'],['PA','Pennsylvania'],['RI','Rhode Island'],
  ['SC','South Carolina'],['SD','South Dakota'],['TN','Tennessee'],['TX','Texas'],
  ['UT','Utah'],['VT','Vermont'],['VA','Virginia'],['WA','Washington'],
  ['WV','West Virginia'],['WI','Wisconsin'],['WY','Wyoming'],
];
