/* CivicView /polls — seed data for the prototype.
   Mix of rep-authored, citizen-on-rep-page, and standalone polls,
   chosen to exercise all three card variants and AI-filter chips.

   `kind`   — used for the small chip on each card (rep / citizen / standalone).
   `branch` — source-type categorization for the top filter chips:
              'bill' | 'committee' | 'executive' | 'judicial' | 'standalone'.
              ('candidate' is reserved for the disabled "From candidates" chip.) */

window.POLLS_SEED = [
  // ----- Rep-authored ----------------------------------------------
  {
    id: 'p1',
    kind: 'rep',
    branch: 'bill',
    source: { code: 'BD · FL-19', label: 'Byron Donalds — FL-19' },
    author: { name: 'Byron Donalds', initials: 'BD', role: 'U.S. Representative · FL-19', avatarTone: 'rep', verified: true },
    time: '14m ago',
    question: 'Should Congress extend the 2025 SALT cap relief through 2030?',
    options: [
      { id: 'a', label: 'Yes — keep relief in place',  votes: 8420, pct: 64, mine: true,  leading: true },
      { id: 'b', label: 'Phase it out gradually',      votes: 3680, pct: 28 },
      { id: 'c', label: 'Let it expire on schedule',   votes: 1050, pct:  8 },
    ],
    totalVotes: 13150,
    comments: 612,
    closesIn: '2d 4h',
    aiTags: ['informative', 'supportive'],
  },
  {
    id: 'p2',
    kind: 'rep',
    branch: 'executive',
    source: { code: 'EXEC', label: 'Executive Branch' },
    author: { name: 'Donald J. Trump', initials: 'DJT', role: 'President of the United States', avatarTone: 'rep', verified: true },
    time: '1h ago',
    question: 'Which infrastructure priority should the administration push first in Q3?',
    options: [
      { id: 'a', label: 'Power grid modernization',     votes: 6720, pct: 42, leading: true },
      { id: 'b', label: 'Port + rail freight upgrades', votes: 4400, pct: 28 },
      { id: 'c', label: 'Interstate bridge backlog',    votes: 3120, pct: 19 },
      { id: 'd', label: 'Rural broadband buildout',     votes: 1750, pct: 11 },
    ],
    totalVotes: 15990,
    comments: 1840,
    closesIn: '6h',
    aiTags: ['critical', 'informative'],
  },
  {
    id: 'p3',
    kind: 'rep',
    branch: 'judicial',
    source: { code: 'SCOTUS', label: 'Supreme Court of the United States' },
    author: { name: 'Office of the Court', initials: 'SC', role: 'Public engagement poll · non-binding', avatarTone: 'rep', verified: true },
    time: '3h ago',
    question: 'Should oral-argument audio be released same-day instead of week-of?',
    options: [
      { id: 'a', label: 'Yes — same-day release',     votes: 9410, pct: 71, leading: true },
      { id: 'b', label: 'Keep the current schedule',  votes: 2880, pct: 22 },
      { id: 'c', label: 'Decide case-by-case',        votes:  920, pct:  7 },
    ],
    totalVotes: 13210,
    comments: 487,
    closesIn: '1d 12h',
    aiTags: ['supportive'],
  },
  {
    id: 'p4',
    kind: 'rep',
    branch: 'committee',
    source: { code: 'CA-12', label: 'Nancy Pelosi — CA-12' },
    author: { name: 'Nancy Pelosi', initials: 'NP', role: 'U.S. Representative · CA-12', avatarTone: 'rep', verified: true },
    time: '5h ago',
    question: 'Where should the next federal climate-resilience grant pilot land?',
    options: [
      { id: 'a', label: 'Coastal flood-zone retrofits', votes: 4220, pct: 38 },
      { id: 'b', label: 'Wildfire defensible-space',   votes: 3680, pct: 33, leading: true, mine: true },
      { id: 'c', label: 'Urban heat-island mitigation', votes: 2110, pct: 19 },
      { id: 'd', label: 'Inland drought watersheds',   votes: 1110, pct: 10 },
    ],
    totalVotes: 11120,
    comments: 298,
    closesIn: '4d',
    aiTags: ['informative', 'positive'],
  },

  // ----- Citizen polls on rep pages ---------------------------------
  {
    id: 'p5',
    kind: 'citizen',
    branch: 'executive',
    source: { code: 'BD · FL-19', label: 'Posted on Byron Donalds\u2019s page' },
    author: { name: 'Marisol Vega', initials: 'MV', role: 'Constituent · FL-19', avatarTone: 'citizen', verified: false },
    time: '22m ago',
    question: 'Has the SW-Florida hurricane-relief portal worked for you this season?',
    options: [
      { id: 'a', label: 'Yes — got a response in under a week', votes:  920, pct: 14 },
      { id: 'b', label: 'Eventually, but it took weeks',        votes: 2410, pct: 38, leading: true },
      { id: 'c', label: 'Submitted and never heard back',       votes: 2180, pct: 34 },
      { id: 'd', label: 'Haven\u2019t needed it',               votes:  870, pct: 14 },
    ],
    totalVotes: 6380,
    comments: 412,
    closesIn: '3d',
    aiTags: ['critical', 'skeptical'],
  },
  {
    id: 'p6',
    kind: 'citizen',
    branch: 'committee',
    source: { code: 'TX-23 (unclaimed)', label: 'Citizen poll on an unclaimed page' },
    author: { name: 'Daniel R. Chen', initials: 'DC', role: 'Constituent · TX-23', avatarTone: 'citizen', verified: false },
    time: '2h ago',
    question: 'Which one issue do you most want the next TX-23 rep to lead on in their first session?',
    options: [
      { id: 'a', label: 'Border-county infrastructure', votes: 1820, pct: 42, leading: true },
      { id: 'b', label: 'Water-rights modernization',  votes: 1130, pct: 26 },
      { id: 'c', label: 'Rural healthcare access',     votes:  900, pct: 21 },
      { id: 'd', label: 'Small-business permits',      votes:  470, pct: 11 },
    ],
    totalVotes: 4320,
    comments: 198,
    closesIn: '12h',
    aiTags: ['informative', 'critical'],
  },
  {
    id: 'p7',
    kind: 'citizen',
    branch: 'committee',
    source: { code: 'NY-14', label: 'Posted on A. Ocasio-Cortez\u2019s page' },
    author: { name: 'Priya Subramaniam', initials: 'PS', role: 'Constituent · NY-14', avatarTone: 'citizen', verified: false },
    time: '6h ago',
    question: 'Town-hall format you\u2019d actually show up to?',
    options: [
      { id: 'a', label: 'In-person, evening, neighborhood-local', votes: 3210, pct: 51, mine: true, leading: true },
      { id: 'b', label: 'Live-streamed with text Q&A',           votes: 1880, pct: 30 },
      { id: 'c', label: 'Saturday morning, central venue',       votes:  720, pct: 12 },
      { id: 'd', label: 'Telephone town hall',                    votes:  430, pct:  7 },
    ],
    totalVotes: 6240,
    comments: 287,
    closesIn: '5d',
    aiTags: ['supportive', 'positive'],
  },

  // ----- Standalone civic polls -------------------------------------
  {
    id: 'p8',
    kind: 'standalone',
    branch: 'standalone',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'CivicView community', initials: 'CV', role: 'Public civic poll', avatarTone: 'standalone', verified: false },
    time: '45m ago',
    question: 'Ranked-choice voting in federal primaries — where do you land?',
    options: [
      { id: 'a', label: 'Adopt nationally',           votes: 9820, pct: 47, leading: true },
      { id: 'b', label: 'Let states decide',          votes: 6720, pct: 32 },
      { id: 'c', label: 'Keep first-past-the-post',   votes: 3680, pct: 18 },
      { id: 'd', label: 'Not sure yet',               votes:  720, pct:  3 },
    ],
    totalVotes: 20940,
    comments: 2104,
    closesIn: '6d',
    aiTags: ['informative', 'critical'],
  },
  {
    id: 'p9',
    kind: 'standalone',
    branch: 'standalone',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'CivicView community', initials: 'CV', role: 'Public civic poll', avatarTone: 'standalone', verified: false },
    time: '3h ago',
    question: 'How much do you trust the federal budget process to deliver this year?',
    options: [
      { id: 'a', label: 'A lot',          votes:  410, pct:  4 },
      { id: 'b', label: 'Some',           votes: 1820, pct: 17 },
      { id: 'c', label: 'Not much',       votes: 4180, pct: 39, leading: true, mine: true },
      { id: 'd', label: 'None at all',    votes: 4280, pct: 40 },
    ],
    totalVotes: 10690,
    comments: 1340,
    closesIn: '1d 6h',
    aiTags: ['skeptical', 'critical'],
  },
  {
    id: 'p10',
    kind: 'standalone',
    branch: 'standalone',
    source: { code: 'Standalone', label: 'Civic topic — not tied to a page' },
    author: { name: 'CivicView community', initials: 'CV', role: 'Public civic poll', avatarTone: 'standalone', verified: false },
    time: '8h ago',
    question: 'Is "civic education in K-12" something Congress should fund directly?',
    options: [
      { id: 'a', label: 'Yes — direct line item',     votes: 5210, pct: 52, leading: true },
      { id: 'b', label: 'State-level block grants',   votes: 2920, pct: 29 },
      { id: 'c', label: 'Private + nonprofit driven', votes: 1410, pct: 14 },
      { id: 'd', label: 'No federal role',            votes:  510, pct:  5 },
    ],
    totalVotes: 10050,
    comments: 762,
    closesIn: '4d',
    aiTags: ['supportive', 'informative'],
  },
  {
    id: 'p11',
    kind: 'rep',
    branch: 'committee',
    source: { code: 'WA-07', label: 'Pramila Jayapal — WA-07' },
    author: { name: 'Pramila Jayapal', initials: 'PJ', role: 'U.S. Representative · WA-07', avatarTone: 'rep', verified: true },
    time: '11h ago',
    question: 'Should the FAA require domestic carriers to publish on-time stats per route, not just per airline?',
    options: [
      { id: 'a', label: 'Yes — per-route disclosure', votes: 7120, pct: 78, leading: true },
      { id: 'b', label: 'Per-airline is enough',      votes: 1480, pct: 16 },
      { id: 'c', label: 'Other / no opinion',         votes:  540, pct:  6 },
    ],
    totalVotes: 9140,
    comments: 318,
    closesIn: '2d',
    aiTags: ['supportive', 'informative'],
  },
  {
    id: 'p12',
    kind: 'citizen',
    branch: 'bill',
    source: { code: 'FL-15', label: 'Posted on L. Lee\u2019s page' },
    author: { name: 'Jasmine O\u2019Connor', initials: 'JO', role: 'Constituent · FL-15', avatarTone: 'citizen', verified: false },
    time: '1d ago',
    question: 'Pick the property-tax reform you\u2019d back if it hit the ballot tomorrow:',
    options: [
      { id: 'a', label: 'Homestead-only deeper cap',         votes:  920, pct: 24 },
      { id: 'b', label: 'Senior + disabled veteran freeze',  votes: 1450, pct: 38, leading: true },
      { id: 'c', label: 'Tier reform for second homes',      votes:  850, pct: 22 },
      { id: 'd', label: 'Hold the line; reform later',       votes:  610, pct: 16 },
    ],
    totalVotes: 3830,
    comments: 142,
    closesIn: '8h',
    aiTags: ['critical', 'informative'],
  },
];

window.AI_FILTER_TAGS = [
  { id: 'positive',    label: 'Positive' },
  { id: 'critical',    label: 'Critical' },
  { id: 'funny',       label: 'Funny' },
  { id: 'supportive',  label: 'Supportive' },
  { id: 'skeptical',   label: 'Skeptical' },
  { id: 'informative', label: 'Informative' },
];
